apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook-event-ingress
  namespace: system
  labels:
    app.kubernetes.io/name: runner-operator
    app.kubernetes.io/managed-by: kustomize
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: webhook.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webhook-event-server
            port:
              number: 80
