## Append samples of your project ##
resources:
- runners_v1alpha1_runner.yaml
- runners_v1alpha1_workflow.yaml
- runners_v1alpha1_runner_git.yaml
- runners_v1alpha1_workflow_git.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
