apiVersion: runners.runner-operator.io/v1alpha1
kind: EventTrigger
metadata:
  labels:
    app.kubernetes.io/name: runner-operator
    app.kubernetes.io/managed-by: kustomize
  name: eventtrigger-sample
spec:
  # TODO(user): Add fields here
