name: Lint

on:
  push:
  pull_request:

permissions: {}

jobs:
  lint:
    permissions:
      contents: read
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod

      - name: Check linter configuration
        run: make lint-config
      - name: Run linter
        run: make lint

  markdownlint:
    permissions:
      contents: read
    name: Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          globs: '**/*.md'
          config: '.markdownlint-cli2.yaml'
